name: Keploy API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  keploy-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./server

      - name: Start the API Server
        run: |
          nohup npm start --prefix ./server &
          sleep 10 # wait for server to start

      - name: Install Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite --app=b89b1c20-1e57-4852-89c4-98d6630b9f86 --base-path=http://localhost:3000 --cloud
